name: environment
channels:
  - r
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - r-tidyr=0.8.3
  - r-ggplot2=3.1.1
  - r-tidyverse=1.2.1
  - r-data.table=1.12.2
  - r-scales=1.0.0
  - r-rcolorbrewer=1.1_2
  - tk=8.6.8
  - tktable=2.10
  - r-tidyselect=0.2.5
  - pip=20.0.2
  - rpy2=2.9.4=py37r36h1d22016_0
  - pip:
    - ipython-sql==0.3.9
