# Script to load libraries
library(metagenomeSeq)
library(tidyr)
library(vegan)
library(ggplot2)
library(tidyverse)
library(phyloseq)
library(data.table)
library(gridExtra)
library(geometry)
library(rgl)
library(scales)
library(gplots)
library(ggrepel)
library(rgl)
library(gridExtra)
library(RColorBrewer)
library(ggthemes)

# library(rtools)
# library(plotly)
# library(plot3D)
# library(gg3D) # https://github.com/AckerDWM/gg3D, library(devtools) , install_github("https://github.com/AckerDWM/gg3D")
# library(ggbiplot) #  install_github("vqv/ggbiplot")
# library(magick)
